name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  CI_IMAGE: pkgbuilder:ci

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log into Docker registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true      
      
      - name: Build image
        uses: docker/build-push-action@v3.1.1
        with:
          pull: true
          push: false
          tags: ${CI_IMAGE}
          outputs: type=docker,dest=/tmp/image.tar
      
      - name: Upload image archive
        uses: actions/upload-artifact@v3
        with:
          name: pkgbuilder-image
          path: /tmp/image.tar

  test:
    name: Test Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download image archive
        uses: actions/download-artifact@v3
        with:
          name: pkgbuilder-image
          path: /tmp/
      
      - name: Import image
        run: docker load --input /tmp/image.tar
      
      - name: Checkout yay repository
        uses: actions/checkout@v3
        with:
          repository: https://github.com/Jguer/yay
      
      - name: Build yay package
        run: |
          cd yay
          docker run --rm -v "${PWD}:/pkg" ${CI_IMAGE}
